### PR TITLE
📤 📉 Fixed extra `didRangeBeacons` transitions

### PR DESCRIPTION
**Pull request by the-bay-kay**
`didRangeBeacons` will no longer send transition notifications during an ongoing trip.

This change should improve both performance and Native Log Legibility.

### CODE REVIEW

**Comment by shankari** [comment]
@the-bay-kay can you please indicate the testing done? Also, please remember to put this into the "Ready for review" column when you are done.

**Comment by shankari** [comment]
@the-bay-kay still waiting for testing done. You also need to bump up the version number in `plugin.xml`, and after I create the release, in the `package.cordovabuild.json`

**Comment by the-bay-kay** [comment]
@shankari This builds and runs successfully! I can open a PR to bump `package.cordovabuild.json` later today.

I've got a few notes / questions:
- Do we want to log the beacon data each time we range?  This is what I'm doing as written.  This will cause quite a few logs during the trip, but that information could be useful for debugging later. 
- With both this build and the previous (master) build, I noticed that `exitRegion` is not immediately triggering the `CFCBeaconLost`, and subsequently, ending the trip.  This could explain some of the unusual tracking behavior seen in some of the trips (located in the internal github repo).  Since that's a bit more of an involved change, I'll be doing that in a different PR.

**Comment by shankari** [comment]
> Do we want to log the beacon data each time we range? This is what I'm doing as written. This will cause quite a few logs during the trip, but that information could be useful for debugging later.

Yes. We can potentially reduce log spew once we get out of beta

> With both this build and the previous (master) build, I noticed that exitRegion is not immediately triggering the CFCBeaconLost, and subsequently, ending the trip. This could explain some of the unusual tracking behavior seen in some of the trips (located in the internal github repo). Since that's a bit more of an involved change, I'll be doing that in a different PR.

Sounds good.

**Pull request merged**
